const s = {
  SKILL_NAME: 'Voice fridge',
  DIME_POR_EJEMPLO: 'Tell me for example: "add milk", "I open the mayonnaise", "info guacamole", "delete the chicken", "show list" or "exit". What do you say?',
  HELP_MESSAGE: 'Say here the food you buy, when you opened it and when it expires. You will waste less food and avoid possible food poisoning. ',
  STOP_MESSAGE: '<say-as interpret-as="interjection">See you later</say-as>',
  NO_ENTIENDO_REPITE_POR_FAVOR: 'I\'m sorry, I haven\'t understood you. Repeat please. ',
  NEVERA_VACIA: 'The fridge is empty. ',
  ERROR_AL_INTENTAR_RECORDAR: 'Error trying to remember what you have in the fridge. Try again. ',
  ERROR_AL_ABRIR_PRODUCTO: 'Error marking product open. Try again. ',
  ERROR_AL_BORRAR_PRODUCTO: 'Error deleting product. Try again. ',
  ERROR_GUARDANDO: 'Error saving product. Try again. ',
  ERROR_INESPERADO: 'An error has occurred. ',
  SOLO_HAY_1_PRODUCTO_EN_NEVERA: 'There is only 1 product in the fridge. ',
  HAY_X_PRODUCTOS_EN_NEVERA: 'There are {0} products in the fridge. ',
  YA_HAY_X: 'There is already {0} in your fridge. ',
  DI_OTRO_O_BORRA: 'Please say another name or say \'remove {0}\'.',
  GUARDADO_X_QUE_CADUCA_EN_Y: 'Saved {0}, which expires {1}. ',
  NO_HE_ENCONTRADO_X: 'I haven\'t found {0} in your fridge. ',
  DI_BORRAR_SEGUIDO_NOMBRE: 'Say \'remove\' followed by the name of the product you want to delete.',
  ELIMINADO_X: '{0} removed. ',
  HOY: 'today',
  AYER: 'yesterday',
  HACE_2_DIAS: '2 days ago',
  MAÑANA: 'tomorrow',
  PASADO_MAÑANA: 'day after tomorrow',
  SE_METIO: 'was saved',
  SE_HA_METIDO: 'was saved',
  ESTA_CERRADO_Y: 'is closed and ',
  CADUCO: 'expired',
  CADUCA: 'expires',
  CADUCARA: 'will expire',
  SE_ABRIO: 'was opened',
  SE_HA_ABIERTO: 'was opened',
  Y: 'and',
  DI_INFO_SEGUIDO_NOMBRE: 'Say \'info\' followed by the product name. ',
  OJO_FECHA_CADUCIDAD_PASADA: 'Eye, you told me an expiration date already passed. I can\'t save it. ',
  OJO_FECHA_CADUCIDAD_ABIERTO_POSTERIOR_A_CERRADO: 'You told me an expiration date after the initial expiration date that was {0}. That\'s not allowed. ',
  ABIERTO_X_CADUCA_EN: '{0} is now opened, it will expire {1}. ',
  EN_LA_NEVERA_HAY: 'In the fridge there are: ',
  SESION_CERRADA: 'The session was closed. Try again.',
  SESION_CERRADA_POR_NO_RESPUESTA: 'The skill was closed for lack of correct user response. Try again.',
  SESION_CERRADA_ERROR: 'The skill was closed due to an error. I\'m sorry, come back in.',
  NINGUN_PRODUCTO_CADUCA_PROXIMOS_2_DIAS: 'No products expire in the next 2 days. ',
  CADUCA_HOY: 'expires today',
  CADUCAN_HOY: 'expire today',
  CADUCA_MANANA: 'expires tomorrow',
  CADUCAN_MANANA: 'expire tomorrow',
  CADUCA_PASADO_MANANA: 'expires the day after tomorrow',
  CADUCAN_PASADO_MANANA: 'expire the day after tomorrow',
  YA_HA_CADUCADO: 'has already expired',
  YA_HAN_CADUCADO: 'have already expired',
};
module.exports = s;
