module.exports = {
  SKILL_NAME: 'Nevera estado',
  DIME_POR_EJEMPLO: 'Dime por ejemplo: "meto leche", "abro la mayonesa", "info guacamole", "borra el pollo" o "ver listado". También puedes salir. ¿Qué dices?',
  HELP_MESSAGE: 'Anota aquí la comida que compras, cuándo la abriste y cuándo caduca. Así desperdiciarás menos comida y evitarás posibles intoxicaciones. ',
  STOP_MESSAGE: '<say-as interpret-as="interjection">Hasta luego</say-as>',
  NO_ENTIENDO_REPITE_POR_FAVOR: '<say-as interpret-as="interjection">¿cómorr?</say-as>. Lo siento, no te he entendido. Repite por favor. ',
  NEVERA_VACIA: 'La nevera está vacía. ',
  ERROR_AL_INTENTAR_RECORDAR: 'Error al intentar recordar lo que tienes en la nevera. Vuelve a intentarlo. ',
  ERROR_AL_ABRIR_PRODUCTO: 'Error al marcar como abierto el producto. Vuelve a intentarlo. ',
  ERROR_AL_BORRAR_PRODUCTO: 'Error borrando. Vuelve a intentarlo. ',
  ERROR_GUARDANDO: 'Error guardando. Vuelve a intentarlo. ',
  ERROR_INESPERADO: 'Ha ocurrido un error. ',
  SOLO_HAY_1_PRODUCTO_EN_NEVERA: 'Hay solo 1 producto en la nevera. ',
  HAY_X_PRODUCTOS_EN_NEVERA: 'Hay {0} productos en la nevera. ',
  YA_HAY_X: 'Ya hay {0} en tu nevera. ',
  DI_OTRO_O_BORRA: 'Por favor di otro nombre o di \'borra {0}\'.',
  GUARDADO_X_QUE_CADUCA_EN_Y: 'Guardado {0}, que caduca {1}. ',
  NO_HE_ENCONTRADO_X: 'No he encontrado {0} en tu nevera. ',
  DI_BORRAR_SEGUIDO_NOMBRE: 'Di \'borrar\' seguido del nombre del producto que quieras borrar.',
  ELIMINADO_X: 'Eliminado {0}. ',
  HOY: 'hoy',
  AYER: 'ayer',
  HACE_2_DIAS: 'hace 2 días',
  MAÑANA: 'mañana',
  PASADO_MAÑANA: 'pasado mañana',
  SE_METIO: 'se metió',
  SE_HA_METIDO: 'se ha metido',
  ESTA_CERRADO_Y: 'está cerrado y ',
  CADUCO: 'caducó',
  CADUCA: 'caduca',
  CADUCARA: 'caducará',
  SE_ABRIO: 'se abrió',
  SE_HA_ABIERTO: 'se ha abierto',
  Y: 'y',
  DI_INFO_SEGUIDO_NOMBRE: 'Di \'info\' seguido del nombre del producto. ',
  OJO_FECHA_CADUCIDAD_PASADA: 'Ojo, me has dicho una fecha de caducidad ya pasada. No puedo guardarlo. ',
  OJO_FECHA_CADUCIDAD_ABIERTO_POSTERIOR_A_CERRADO: 'Ojo, me has dicho una fecha de caducidad posterior a la fecha de caducidad inicial que era {0}. Eso no se puede. ',
  ABIERTO_X_CADUCA_EN: 'Abierto {0}, ahora caduca {1}. ',
  EN_LA_NEVERA_HAY: 'En la nevera hay: ',
  SESION_CERRADA: 'Se cerró la sesión. Vuelve a entrar.',
  SESION_CERRADA_POR_NO_RESPUESTA: 'La skill se cerró por falta de respuesta correcta del usuario, vuelve a entrar.',
  SESION_CERRADA_ERROR: 'La skill se cerró por un error. Lo siento, vuelve a entrar.',
  NINGUN_PRODUCTO_CADUCA_PROXIMOS_2_DIAS: 'Ningún producto caduca en los próximos 2 días. ',
  CADUCA_HOY: 'caduca hoy',
  CADUCAN_HOY: 'caducan hoy',
  CADUCA_MANANA: 'caduca mañana',
  CADUCAN_MANANA: 'caducan mañana',
  CADUCA_PASADO_MANANA: 'caduca pasado mañana',
  CADUCAN_PASADO_MANANA: 'caducan pasado mañana',
  YA_HA_CADUCADO: 'ya ha caducado',
  YA_HAN_CADUCADO: 'ya han caducado',
};
